name: GitHub Pages
on: push
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v4
      - name: Install dependencies
        run: pnpm i
      - name: Build application
        run: pnpm build
      - name: Remove all files except dist directory
        run: find . -maxdepth 1 ! -name 'dist' ! -name '.git' ! -name '.' -exec rm -rf {} +
      - name: Push to gh-pages
        run: |
          git checkout -b gh-pages
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Release project"
          git push