name: GitHub Pages
on:
  push:
    branches:
      - main
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: 'main'
      - uses: pnpm/action-setup@v4
      - name: Install dependencies
        run: pnpm i
      - name: Build application
        run: pnpm build
      - name: Remove all files except dist directory
        run: find . -maxdepth 1 ! -name 'dist' ! -name '.git' ! -name '.' -exec rm -rf {} +
      - name: Move dist to temporary docs directory
        run: mv dist $RUNNER_TEMP/docs
      - uses: actions/checkout@v3
        with:
          ref: 'gh-pages'
          clean: false
      - name: Replace docs directory with the new one
        run: |
          rm -rf docs
          mv $RUNNER_TEMP/docs docs
      - name: Push to gh-pages
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Release project"
          git push